version: '3'
services:
  todo:
    build: 
      context: .
      dockerfile: Dockerfile
    image: todo-task
    cap_add:
      - NET_ADMIN
    container_name: todo-task
    restart: unless-stopped


    ports:
      - "3003:3003"
    volumes:
      - .:/node/app
  
    command: npm run start